version: '3.7'

services:
  gatsby:
    build:
      context: .
      target: gatsby
    volumes:
      - ./src:/src
    working_dir: /src/big_smoke_web_site
    entrypoint: gatsby develop --host=0.0.0.0  --port=8024
    ports:
    - "8024:8024"
